In [23]:
import numpy as np
ani = np.arange(6)
print(ani) # prints the range from 0 to 6

# Printing the odd parts only
b=ani[ani%2==1]   # array_name[conditon(or required array to print)]
print(b)

# Changing the odd parts to -1
c = np.where(ani%2==1,-1,ani)   # Used to change/replace any element of array
print(c)

d = np.where(ani[2]==2,0,ani)  # true for all elements of the array
print(d)

e = np.where(ani==2,0,ani) # to change a specific element
print(e)

ket = np.array([1,3,5,3,7,9])
tek = np.intersect1d(ani,ket)  # to find common element between two elements
print(tek)

# position of common elements between two arrays
print(np.where(ani==ket))

[0 1 2 3 4 5]
[1 3 5]
[ 0 -1  2 -1  4 -1]
[0 0 0 0 0 0]
[0 1 0 3 4 5]
[1 3 5]
(array([3], dtype=int64),)


In [25]:
# Used for adding the elements
f = np.append(ani,[34,60,63])
print(f)

[ 0  1  2  3  4  5 34 60 63]


In [26]:
print(ani*ket)

[ 0  3 10  9 28 45]


In [29]:
print(type(ani))

<class 'numpy.ndarray'>
