In [2]:
import numpy as np

In [7]:
# zero dimensional array
c = np.array(42)
print(c)

42


In [6]:
# one dimensional array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# two dimensional array
b = np.array([[1,2,3],[3,2,1]])
print(b)
print(b.shape) # gives the shape of matrix

[[1 2 3]
 [3 2 1]]
(2, 3)


In [4]:
print(b.reshape(3,2)) # reshapes the matrix 

[[1 2]
 [3 3]
 [2 1]]


In [5]:
print(b.transpose()) # prints the transpose of the matrix

[[1 3]
 [2 2]
 [3 1]]


In [8]:
# for making n number of copy 
d = np.tile(b,4)
print(d)

e = np.tile(b,reps=[2,2]) # [x,y] or reps=[x,y]
print(e)

f = np.tile(b,[3,2])
print(f)

[[1 2 3 1 2 3 1 2 3 1 2 3]
 [3 2 1 3 2 1 3 2 1 3 2 1]]


In [16]:
ket = np.array([[2,4,6],[1,2,3]])
# con = np.concatenate((b,ket))  # for merging two arrays 'ket' and 'b' 
con = np.concatenate((b,ket),axis = 1)  # axis = 1 => merge along y axis, by default axis = 0 => merge along x axis 
print(con)


[[1 2 3 2 4 6]
 [3 2 1 1 2 3]]


In [18]:
# Mathematical Operations
print(b + ket)
print(b/ket)

[[3 6 9]
 [4 4 4]]
[[0.5        0.5        0.5       ]
 [3.         1.         0.33333333]]


In [19]:
# for converting 'int' array to 'float'
print(b.astype(float))

[[1. 2. 3.]
 [3. 2. 1.]]
